language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
